# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especie',
            options={'verbose_name_plural': 'Espécies'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name_plural': 'Pets'},
        ),
        migrations.AlterModelOptions(
            name='raca',
            options={'verbose_name_plural': 'Raças'},
        ),
    ]
