# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20171117_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Adotado', 'Adotado')], default='Disponível', max_length=20),
        ),
    ]
