# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
