# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20171120_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, upload_to='img_pets'),
        ),
    ]
