# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20171120_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, default='static/img/user.png', upload_to='img_user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefone',
            field=models.CharField(default='teste', max_length=30),
            preserve_default=False,
        ),
    ]
