# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20171120_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
