# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0010_auto_20171120_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.CreateModel(
            name='PetQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.AddField(
            model_name='petanswer',
            name='pet_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.PetQuestion'),
        ),
        migrations.AddField(
            model_name='petanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
