# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0012_petquestion_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.CharField(choices=[('1 a 3 meses', '1 a 3 meses'), ('3 a 6 meses', '3 a 6 meses'), ('6 a 9 meses', '6 a 9 meses'), ('9 a 12 meses', '9 a 12 meses'), ('1 a 3 anos', '1 a 3 anos'), ('Acima de 3 anos', 'Acima de 3 anos')], default='1 a 3 meses', max_length=20)),
                ('genero', models.CharField(choices=[('Fêmea', 'Fêmea'), ('Macho', 'Macho')], default='Fêmea', max_length=20)),
                ('status', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Adotado', 'Adotado')], default='Solicitado', max_length=20)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Especie')),
                ('raca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Raca')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Interesse',
            },
        ),
        migrations.AlterField(
            model_name='pet',
            name='genero',
            field=models.CharField(choices=[('Fêmea', 'Fêmea'), ('Macho', 'Macho')], default='Fêmea', max_length=20),
        ),
    ]
