# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20171124_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interesse',
            options={'verbose_name_plural': 'Quero adotar'},
        ),
    ]
